// Action Types for Getting User Watchlist
export const GET_USER_WATCHLIST_REQUEST = "GET_USER_WATCHLIST_REQUEST";
export const GET_USER_WATCHLIST_SUCCESS = "GET_USER_WATCHLIST_SUCCESS";
export const GET_USER_WATCHLIST_FAILURE = "GET_USER_WATCHLIST_FAILURE";

// Action Types for Adding Coin to Watchlist
export const ADD_COIN_TO_WATCHLIST_REQUEST = "ADD_COIN_TO_WATCHLIST_REQUEST";
export const ADD_COIN_TO_WATCHLIST_SUCCESS = "ADD_COIN_TO_WATCHLIST_SUCCESS";
export const ADD_COIN_TO_WATCHLIST_FAILURE = "ADD_COIN_TO_WATCHLIST_FAILURE";
